services:
  resource-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: resource-db
    ports:
      - "5432:5432"

  song-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: song-db
    ports:
      - "5433:5432"
