server:
  port: 8080

spring:
  application:
    name: gateway-service

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_HOST:localhost}:8761/eureka