server:
  port: 8082

spring:
  application:
    name: song-service
  datasource:
    url: ${SONG_DB_URL:jdbc:postgresql://localhost:5433/song-db}
    username: ${SONG_DB_USERNAME:postgres}
    password: ${SONG_DB_PASSWORD:postgres}
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_HOST:localhost}:8761/eureka