server:
  port: 8081

spring:
  application:
    name: resource-service
  datasource:
    url: ${RESOURCE_DB_URL:jdbc:postgresql://localhost:5432/resource-db}
    username: ${RESOURCE_DB_USERNAME:postgres}
    password: ${RESOURCE_DB_PASSWORD:postgres}
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

song:
  host:
    url: http://${SONG_SERVICE_HOST:localhost}:8082/songs

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_HOST:localhost}:8761/eureka