server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/resource-db
    username: ${RESOURCE_DB_USERNAME:postgres}
    password: ${RESOURCE_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null

song:
  host:
    url: http://localhost:8081/songs
